const file=require('fs')
// file.mkdirSync("thapa")
// file.writeFileSync("./thapa/bio.txt","This is a test")
// file.appendFileSync("./thapa/bio.txt","This is the appending function use")
// const txt=file.readFileSync("./thapa/bio.txt")
// console.log(txt.toString())    
// file.renameSync("./thapa/bio.txt",'./thapa/mybio.txt')
file.unlinkSync("./thapa/mybio.txt")
file.rmdirSync("./thapa")
